import '@styles/globals.css'
import { Inter } from 'next/font/google';
import { Metadata } from 'next'
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata:Metadata = {
  title      : 'Create Next App',
  description: 'Generated by create next app',
  keywords   : 'Hello World',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
